# Update dependencies

version: 2
updates:
# Update the Github Action  versions
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
  - "automerge"
  - "enhancement"
